--====================================================== 
-- Seth Huffman
-- CIS332: Database and SQL
-- UNIT 5, CHAPTER 7 Assignment
--======================================================

-- Number 1
CREATE USER SHUFFMAN IDENTIFIED BY applepie2025;

-- Number 3
GRANT CREATE SESSION TO SHUFFMAN; 
GRANT CREATE TABLE TO SHUFFMAN;
GRANT ALTER ANY TABLE TO SHUFFMAN;

-- Number 4
CREATE ROLE CUSTOMERREP;
GRANT INSERT, DELETE ON ORDERS TO CUSTOMERREP;
GRANT INSERT, DELETE ON ORDERITEMS TO CUSTOMERREP;

-- Number 6
CONNECT SHUFFMAN/applepie2025;
SELECT * FROM SESSION_PRIVS;
SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_TAB_PRIVS;

-- Number 9
DROP ROLE CUSTOMERREP;
