# Generated by Django 5.2.3 on 2025-07-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
